services:
  postgres:
    image: postgres:18
    container_name: php-basic-postgres
    environment:
      POSTGRES_DB: php_basic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
